name: Live Wonderstruck Sanctuary
favicon: null
layout_spectrum: 0.7360436585731804
typography_spectrum: 0.40723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f8f9'
    - '#393945'
    - '#fd9294'
    - '#000000'
    - '#676770'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.0017937885131686926
  rhythmicContrast: 0.0860543001908809
purpose: []
