name: null
favicon: null
layout_spectrum: 0.7360436585731804
typography_spectrum: 0.18538374034687877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.07857515360228717
  lightness: 0.5763363149017096
  saturation: 0.0017937885131686926
  rhythmicContrast: 0.0860543001908809
purpose: []
